"""add file model

Revision ID: a2afc4c78704
Revises: c2263de885b5
Create Date: 2026-03-18 08:47:03.257797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2afc4c78704'
down_revision = 'c2263de885b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('type_file', sa.String(length=50), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('tache_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tache_id'], ['tache.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    # ### end Alembic commands ###
