"""add tache model

Revision ID: ce69f54a3fb2
Revises: 90b436d113b4
Create Date: 2026-03-18 07:06:41.301075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce69f54a3fb2'
down_revision = '90b436d113b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('projet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['projet_id'], ['projet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tache')
    # ### end Alembic commands ###
